services:
  sync:
    image: knifez/ug-videokeeper:latest
    container_name: ug-videokeeper-sync
    restart: unless-stopped
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_NAME=video
      - DB_USER=postgres
      - DB_PASSWORD=
      - SCAN_INTERVAL=3600
      - SYNC_MODE=bidirectional
      - DRY_RUN=false
      # - TARGET_PATH=/volume1/media/movie
      - LOG_LEVEL=INFO
    volumes:
      - 你的绿联媒体目录:/你的绿联媒体目录
      - ./data:/app/data
    network_mode: "host"          # 使用主机网络模式（保证服务发现正常）
    command: ["python", "main.py"]

  web:
    image: knifez/ug-videokeeper:latest
    container_name: ug-videokeeper-web
    restart: unless-stopped
    depends_on:
      - sync
    ports:
      - "8088:8088"
    volumes:
      - ./data:/app/data
    command: ["python", "main.py", "--serve"]
